name: Build and Test (Release)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{matrix.os}}

    steps:
    - name: Setup C/C++ Compiler
      uses: rlalik/setup-cpp-compiler@v1.1
      id: install_cc
      with:
        compiler: clang++-12

    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install System Packages
      run: sudo apt-get update && sudo apt-get -y install python3 python3-pip

    - name: Install Python Packages
      run: pip3 install

    - name: Configure Conan Profile
      run: conan profile new --detect default &&
        conan profile update settings.compiler=clang default &&
        conan profile update settings.compiler.version=12 default &&
        conan profile update settings.build_type=${{env.BUILD_TYPE}} default

    - name: Build
      working-directory: ${{github.workspace}}
      run: conan create -pr:b default .

    # - name: Configure CMake
    #   # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
    #   # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
    #   run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    #   env:
    #     CC: ${{ steps.install_cc.outputs.cc }}
    #     CXX: ${{ steps.install_cc.outputs.cxx }}

    # - name: Build
    #   # Build your program with the given configuration
    #   run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    # - name: Test
    #   working-directory: ${{github.workspace}}/build
    #   # Execute tests defined by the CMake configuration.
    #   # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
    #   run: ctest -C ${{env.BUILD_TYPE}}
