name: Build and Test (Release)

on:
  push:
    branches: [ "master", "feat/**", "chore/**" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  CTEST_OUTPUT_ON_FAILURE: ON

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{matrix.os}}

    steps:
    - name: Setup C/C++ Compiler
      uses: rlalik/setup-cpp-compiler@v1.1
      id: install_cc
      with:
        compiler: clang++-12

    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install System Packages
      run: sudo apt-get update && sudo apt-get -y install python3 python3-pip

    - name: Install Python Packages
      run: pip3 install conan

    - name: Configure Conan Profile
      run: |
        cat > ./conan-profile <<EOF
        [settings]
        compiler=clang
        compiler.version=12
        compiler.libcxx=libstdc++11
        build_type=${{env.BUILD_TYPE}}
        EOF

    - name: Build and Test
      working-directory: ${{github.workspace}}
      run: conan create -pr:b ./conan-profile --build missing .
      env:
        CC: ${{ steps.install_cc.outputs.cc }}
        CXX: ${{ steps.install_cc.outputs.cxx }}
